### ISSUE TITLE
sys_file_reference empty

### ISSUE THREAD

**Issue by sinasita** [netresearch/t3x-nr_dam_falmigration#1]
I just used your extension but without having the files physically available. So the sys_files table is full of entries, but the sys_file_reference table is empty without any entry and the whole tt_content has in its image-column the filenames from before. Do you have any idea, what the problem could be? And how could i start the transformation again or undo it? Thanks in advance

**Comment by copitz** [comment]
1. You don't need the files to be physically available - only the tx_dam\* tables
2. The extension migrates the references from tx_dam_mm_ref - do you have this table available?
   (when you have filenames in tt_content - did this field use the dam records at all?)
3. You can simply truncate sys_file and sys_file_metadata and rerun the migration in order to try it again
   Good luck

**Comment by sinasita** [comment]
Oh thanks for your help, that was the right hint. It's a system with dam installed, but nothing more. So there are no references. The step "Migrate all file relations from tt_content.image and pages.media" did the trick and was enough, only the files where still missing.
